{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tengen.fullname" . }}
  labels:
    {{- include "tengen.labels" . | nindent 4 }}
type: Opaque
stringData:
  google-api-key: {{ .Values.secrets.googleApiKey | quote }}
  rabbitmq-url: {{ include "tengen.rabbitmqUrl" . | quote }}
  splunk-hec-url: {{ .Values.secrets.splunkHecUrl | quote }}
  splunk-hec-token: {{ .Values.secrets.splunkHecToken | quote }}
  splunk-es-host: {{ .Values.secrets.splunkEsHost | quote }}
  splunk-es-token: {{ .Values.secrets.splunkEsToken | quote }}
  pagerduty-api-key: {{ .Values.secrets.pagerdutyApiKey | quote }}
  universal-http-token: {{ .Values.secrets.universalHttpToken | quote }}
  azure-tenant-id: {{ .Values.secrets.azureTenantId | quote }}
  azure-client-id: {{ .Values.secrets.azureClientId | quote }}
  azure-client-secret: {{ .Values.secrets.azureClientSecret | quote }}
  crowdstrike-client-id: {{ .Values.secrets.crowdstrikeClientId | quote }}
  crowdstrike-client-secret: {{ .Values.secrets.crowdstrikeClientSecret | quote }}
{{- end }}
