apiVersion: v1
kind: Service
metadata:
  name: {{ include "tengen.fullname" . }}-ingest
  labels:
    {{- include "tengen.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ingest.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tengen.componentLabels" (dict "root" . "component" "ingest") | nindent 4 }}
